### ISSUE TITLE
Serialize posts_controller#index response with a custom serializer which does not contain unnecessary includes

### ISSUE THREAD

**Issue by begedin** [code-corps/deprecated-code-corps-rails-api#106]
Not actually sure if we should go with a custom serializer, or just use the same one, but not include the usual includes. We should probably research what the convention is.

The way I see it, with a has_many relationship, we would need big database fetches, which isn't great, so  our serializer probably shouldn't have any `has_many` relationships. `belongs_to` should be fine, since the id for that is contained within the record.

Maybe these lower-footprint serializers for index methods should only contain `belongs_to` relationships, no `includes` and `x_counter` fields for their `has_many` relationships?

**Comment by joshsmith** [comment]
I think the counter caches are immune from needing the `includes`, am I wrong? Otherwise agree with what you said.
