### ISSUE TITLE
Add roles to team and organization memberships

### ISSUE THREAD

**Issue by begedin** [code-corps/deprecated-code-corps-rails-api#119]
This would be a good place to discuss those roles before we start a PR.

What should they be for organizations and teams?

Here's my initial draft (higher role can do lower role actions)
- Organizations
  - Owner - CRUD organization, CRUD organization memberships for everyone
  - Admin - can CRUD teams, CRUD team memberships, CRUD organization memberships for members
  - Member - basic level, not sure if it gives the user any abilities
- Teams
  - Admin - CRUD their team. CRUD team memberships of their team, CRUD team projects
  - Member - basic level, not sure if any abilities

**Comment by joshsmith** [comment]
I think the following should be the case:

### Organizations
- Owner
  - CRUD organization
  - CRUD organization memberships
- Admin
  - CRUD teams
  - CRUD team memberships
  - CRUD organization memberships for members
- Member
  - CRUD on all projects within organization

### Teams
- Admin / Member permissions on specific projects

**Comment by joshsmith** [comment]
Team permissioning needs #144

**Comment by joshsmith** [comment]
Closing due to #175.
