### ISSUE TITLE
`InitializeNewFacebookUserWorker` calls `UpdateUsersLeaderboardsWorker`, which does not exist.

### ISSUE THREAD

**Issue by begedin** [code-corps/deprecated-code-corps-rails-api#125]
This is happening in `users_controller#create`, when registering a user through Facebook. Since the worker doesn't do anything else, I think it's best to remove it altogether.

**Comment by joshsmith** [comment]
I won't be removing the worker, but adding a worker in there since there with #85

**Comment by joshsmith** [comment]
Nevermind, will remove it.
