### ISSUE TITLE
Add GitHub repository model

### ISSUE THREAD

**Issue by joshsmith** [code-corps/deprecated-code-corps-rails-api#14]
We need a model that includes a `title`, `organization`, `repository name` for a GitHub repository. A project should be able to have many of these.

Not sure what the proper name for this is.

**Comment by scarfdestroyer** [comment]
Could we integrate the model for the repos and the adding them to the project description? For example, if you want to add a repo you give the API the URL, we parse it and get the information from Github and automatically create a "repository" model that associated with the project with the repository's info.
