### ISSUE TITLE
Find permissions for a user and project through teams

### ISSUE THREAD

**Issue by joshsmith** [code-corps/deprecated-code-corps-rails-api#146]
Let's proceed by example.

Code Corps has API team and Ember team. The API team has access to `code-corps-api` and the Ember team has access to `code-corps-ember`. Josh is on the API team. We need to check Josh's access to the `code-corps-ember` project.

In order to do this for any user, we must first get a user’s team memberships. From those teams, we can access their `TeamProject`'s, which will tell us the privileges of that team. Through these relationships we can infer Josh's access to the given project.

**Comment by joshsmith** [comment]
From a quick code spike we should be able to do something like the following:

``` ruby
team_ids = user.teams.pluck(:id)
team_projects = TeamProject.where(team: team_ids)
team_projects.max_by { |x| x.admin? ? 1 : 0 }
```

Seems hacky, but it works in theory.

**Comment by joshsmith** [comment]
We would then have this:

``` ruby
class TeamProject < ActiveRecord::Base
  enum role: {
    regular: "regular",
    admin: "admin"
  }

  # Stored in order from least permissive to most permissive
  ROLES = ["regular", "admin"]

  def role_value
    ROLES.index(self.role)
  end
end
```

Which would let us do:

``` ruby
team_projects.max_by { |team_project| team_project.role_value }
```

This has the downside of assuming our role values are always discretely ordered, but in this case that assumption holds better than assuming we should assign integer values to our `enum` and have to deal with intermediate migrations later on.

Instead, the logic for `find_most_permissive_team_project_for_user(user)` (or something like this) would look like our `max_by`.

**Comment by estiens** [comment]
What is the theory behind doing this all DIY rather than using something like CanCanCan to manage all permissions? In general, I don't like having to have ordered anything, at the very least it should be a hash of roles mapped to numbers I think

**Comment by joshsmith** [comment]
@estiens we're using [`Pundit`](https://github.com/elabs/pundit) but the policies are relatively complex. Looking for user-level permissions, project-level permissions, organization-level permissions, and team-granting permissions.

**Comment by joshsmith** [comment]
So you're thinking of something like:

``` ruby
  ROLES = {
    "regular" => 0,
    "admin" => 1
  }

  def role_value
    ROLES[self.role]
  end
```

**Comment by estiens** [comment]
Yes, exactly, anything to make that ordering explicit rather than implicit.

**Comment by scarfdestroyer** [comment]
We need a way to be able to add and change the level that people are at (admin or regular) on team projects do this mean we will need
    - Policy for Team Projects
    - Spec for the policy
    - Controller to accept CRUD actions for the team projects

What does admin and regular mean? Is it something the organization defines? 

Basically the above keeps me from figuring out:
    - What actions need to first do a team project check with your logic in the issue?
    - Should the logic be brought out as a helper so we can test the logic as a whole rather than for each action?

**Comment by joshsmith** [comment]
`admin` and `regular` are permission levels for a given project. You're either a regular user with normal permissions, or an `admin` user with special permissions. It's pretty binary right now. It's not defined by the organization, but our own definition of what those permissions look like. I think there's a pretty extensive discussion of that elsewhere.

**Comment by joshsmith** [comment]
There will need to be a controller for CRUD for team projects.

**Comment by scarfdestroyer** [comment]
So if a user is a contributor their permissions can be raised to an admin status but just on a certain project?

**Comment by joshsmith** [comment]
A policy for `TeamProject` would involve checking for admin permissions for that project or for the organization.

**Comment by joshsmith** [comment]
> So if a user is a contributor their permissions can be raised to an admin status but just on a certain project?

Yes, exactly. This is granular permission granting.

Imagine a scenario where we want to give someone on the API admin abilities on the API project, but nowhere else. We'd add them to a special "API core team" team that grants those admin abilities on that project, and maybe just "regular" abilities on every other project.

**Comment by scarfdestroyer** [comment]
Okay then, I guess the last unknown is really just where the logic should live. Seems like it has the potential to need to be used in different places so i'm not sure its the best idea to bloat other models with the same code.

**Comment by joshsmith** [comment]
Write it in one place first and then extract it. Don't try to refactor from square one. Get it to work in one place and you'll see how you like the API. Then you can adapt it from there.

**Comment by joshsmith** [comment]
Closing due to #175.
