### ISSUE TITLE
Determine if there are specific attributes that should be restricted in our models

### ISSUE THREAD

**Issue by joshsmith** [code-corps/deprecated-code-corps-rails-api#147]
Pundit allows us the ability to use Rails' strong parameters to [enforce parameter-level checks for different users](https://github.com/elabs/pundit#strong-parameters). We should audit whether there are any parameters in use now (or future parameters that we can foresee) that would need restricted.

**Comment by begedin** [comment]
First things that comes to mind is `OrganizationMembership` where we should only be able to update the role field, not the member or organization association.

**Comment by joshsmith** [comment]
Closing as irrelevant because moving to Phoenix.
