### ISSUE TITLE
Add .env.example

### ISSUE THREAD

**Issue by joshsmith** [code-corps/deprecated-code-corps-rails-api#155]
For onboarding happiness. Ex:

https://github.com/aortbals/southwest-checkin/blob/master/.env.example

**Comment by hbrysiewicz** [comment]
Ran into this issue when setting up api/ember today, as well. +1

**Comment by joshsmith** [comment]
There should also be documentation on how to get this set up.

Of particular concern are credentials. We need to balance sandboxing off development contributions while ensuring least amount of headaches in setup.
