### ISSUE TITLE
Add `modelType` and `ownerType` properties to `MemberSerializer` and `ProjectSerializer` respectively

### ISSUE THREAD

**Issue by begedin** [code-corps/deprecated-code-corps-rails-api#164]
If there are other serializers used for the same models, they should likely have those to, provided they serialize the `member` and `owner` relationships.

**Comment by joshsmith** [comment]
Should this be closed?

**Comment by begedin** [comment]
Yeah, definitely. This is obsolete with the relationship changes. I can outright close it myself.
