### ISSUE TITLE
Add posts to individual project endpoint

### ISSUE THREAD

**Issue by joshsmith** [code-corps/deprecated-code-corps-rails-api#17]
When retrieving an individual project, we should get the posts that project has.

**Comment by begedin** [comment]
Since the posts endpoint will have pagination, should we just be getting the first page of posts here, somehow? Or maybe we should be getting just posts with status open?

Should the records be included, or just the relationships?

**Comment by joshsmith** [comment]
@begedin is there a better way to do this on ember side probably? And API endpoint for `/projects/:id/posts` or something would hit that anyway.

**Comment by begedin** [comment]
I'm not sure exactly, but generally speaking, I don't think ember likes using nested routes on it's own.

There's a [linking feature defined in JSON API](http://jsonapi.org/format/#document-links), where you can specify links for related records in the parent record. This link would be an URL to the route that retrieves those related records. 

I'm not sure if ember-data already supports this feature. If it does, then a nested route makes sense.

Assuming it doesn't, the default behavior is that it will check the relationships object on the project, figure out there's a posts relationship and then, if those posts aren't in the `included` object, fetch them using the  `"GET /posts/"` route, using an array of ids as a parameter.

For us this means
- If ember data supports links, implement that feature on the API side, and expose the nested route
- If it doesn't, add support for filtering through an array of ids on the `GET /posts` endpoint
- Either way, we need to decide how many records, if any, we include with the `project` record itself.

**Comment by begedin** [comment]
@JoshSmith The more I think about it, the more sense it makes to me not to include anything except maybe the relationships part (not actual include).

The way I see it, it's easier to fetch posts via `GET /posts?filter[project_id]=x&page[number]=y&page[size]=z`, which is the standard way of doing it.

In the case of an RSpec get request, this would be equivalent to

``` Ruby
get /posts, { filter: { project_id: x }, page: { number: y, size: z } }
```

Basically, I'm thinking most client apps will have a project page, with either special sections or subpages containing posts in general, or per category. We can add pagination to those subsections, which will then trigger requests to get the first page of posts for that specific project, with controls to switch pages.

In the case of an Ember app, it would be

``` Handlebars
{!  project details component}
{! basic details go here}
{post-list-component category=task pageSize=20}
```

The post list component would then fetch the first page of posts and have controls which fetch other pages, based on how we want to implement it. 

This way, we don't need to include anything.

**Comment by joshsmith** [comment]
Does this need to be closed?

**Comment by begedin** [comment]
I believe so. Currently, we're fetching posts explicitly, after loading the project. As we discussed, we're avoiding having includes with the project. Relationships are fine, but includes are an issue.
