### ISSUE TITLE
Routing needs to be nested

### ISSUE THREAD

**Issue by joshsmith** [code-corps/deprecated-code-corps-rails-api#197]
The Ember app has URLs like `code_corps/code_corps/posts/18`, which we can break this down into its component parts: `:slugged_route_slug/:project_slug/posts/:number`.

When making a request to the API, the Ember app, if hit directly at that URL, has _no knowledge_ of the `Project` `id`, or of any `id` at all!

This means that in order to find the project for a particular post, you would first have to do something like the following:

```
      Organization.find_by_slug(slugged_route_slug)
        .projects
        .find_by_slug(project_slug)
```

This means we need to change our routes to something like the following:

```
    resources :slugged_routes, path: '', only: [:show] do
      get "projects", to: "projects#index"
      resources :projects, path: '', only: [:show] do
        resources :posts, only: [:index, :show]
      end
    end
```

I don't see any way around this given the constraints we have.

We need to make a listing of all the possible routes, and what the Ember app could possible know or not know.

**Comment by begedin** [comment]
Looking at the code at both sides, 
1. Ember thinks the route for fetching a specific post from the API should be

```
GET /:member_slug/:project_slug/posts/:number
```
1. The API thinks the route is 

```
GET /projects/:id/posts/:number
```

This could be handled without modifying the API, though.

The way ember routing works is that the router goes through the nested route hierarchy in order, so it will hit the project route first and fetch the project, I'm pretty sure (though I can't really check at the moment, internet issues), so technically, we do have access to the project id and it would just be a matter of fixing it in `adapters/post`.

Or we could nest, which would also work for me, in which case, whatever we decide in https://github.com/code-corps/code-corps-ember/issues/61 wont affect us here.

**Comment by joshsmith** [comment]
Ember changes allow this to work without issue.
