### ISSUE TITLE
Add contributors counts to project endpoint

### ISSUE THREAD

**Issue by joshsmith** [code-corps/deprecated-code-corps-rails-api#20]
We should have a counter cache column for the number of contributors to a given project.

**Comment by begedin** [comment]
Blocked by #12

**Comment by joshsmith** [comment]
I'm assigning this to @scarfdestroyer. Don't take this on @begedin.

**Comment by begedin** [comment]
@JoshSmith Sorry, I didn't realize your [comment](https://github.com/code-corps/code-corps-api/issues/20#issuecomment-161536686). In any case, @scarfdestroyer did most of the work by adding the counter cache feature. I did the rest in #108, by adding the field to the `ProjectSerializer` and `ProjectSerializerWithoutIncludes`, so this can be closed.
