### ISSUE TITLE
Add a CONTRIBUTING.md

### ISSUE THREAD

**Issue by ptrikutam** [code-corps/deprecated-code-corps-rails-api#215]
Basic instructions on how to contribute & determine what to work on would be great. This can include:
- Issue management
- Submitting PRs (labels / etc)
- Preferred git workflows?

Some guides that thoughtbot provides: https://github.com/thoughtbot/guides. These might be a good place to start.

**Comment by joshsmith** [comment]
Much needed.

**Comment by ptrikutam** [comment]
A quick win would be to point to Thoughtbot's great guides. I notice we're using a `develop` branch here but for the early stages of this we could potentially use the thoughtbout / [github flow](https://guides.github.com/introduction/flow/).
