### ISSUE TITLE
Fix Base64ImageDecoder to not force png

### ISSUE THREAD

**Issue by joshsmith** [code-corps/deprecated-code-corps-rails-api#218]
This doesn't seem to have any real effect on the file type itself (tested on a `.gif`, for example, still works like a GIF). It's not clear that it's even needed, per se, except for setting the filename. But it would be best if images are appended with the correct file type instead of `.png` regardless.

**Comment by scarfdestroyer** [comment]
Would you consider more Regex to be the wrong way to go here? It seems like it would be too brittle of code unless we are committing for a while at least to assume all of our base64 data is going to have the image data headers embedded in the beginning. If not I think I have something worked out that would be useful.

**Comment by joshsmith** [comment]
Closing as irrelevant because moving to Phoenix.
