### ISSUE TITLE
Add a PostLike or similar model

### ISSUE THREAD

**Issue by joshsmith** [code-corps/deprecated-code-corps-rails-api#22]
We want the ability to "like" posts, so we need a way for users to like them. There should probably be a counter cache column for this as well.

**Comment by begedin** [comment]
My proposal:
- `post_likes` table
  - belongs to user
  - belongs to post, with counter cache
- `posts` gets a `post_likes_count` column
- `PostLike` model validates uniqueness of `user_id`, scoped to`post_id`
- `/post_likes` endpoint has a `POST` and `DELETE` action
