### ISSUE TITLE
Consider measuring project health with metrics

### ISSUE THREAD

**Issue by joshsmith** [code-corps/deprecated-code-corps-rails-api#221]
We should consider how to measure project health, if only as an internal mechanism to warn us when projects need help. Issue stats (http://issuestats.com/) is a good example. Ember Addons (https://www.emberaddons.com/) health scores are maybe even better.

We need to be able to identify if issues are not being tended quickly.

Of course, these quantitative metrics are not enough. We need to be constantly getting qualitative feedback about project health. But it should at least serve as a canary in the coal mine for us.

**Comment by gcollazo** [comment]
@JoshSmith the score displayed on emberaddons.com is from emberobserver.com you should talk with @kategengler who is doing an amazing job at curating and evaluating each individual addon on the site.

**Comment by joshsmith** [comment]
Awesome, thanks @gcollazo! :+1:

**Comment by kategengler** [comment]
Hi @JoshSmith. What are you looking to do here?

The current score on EmberObserver is comprised of:

1 point is given for every 'Yes' answer in the review. (Five questions: Is it OSS?, Is it non-empty?, Are there meaningful tests?, Are there any docs?, Is there a CI build?)
1 point is given for a recent release (within last 3 months).
1 point is given for more than 1 commit within the last 3 months.
1 point is given for having more than 1 contributor.
1 point is given for having a download count in the last 30 days that is in the top 10% for all addons.
1 point is given for having a Github star count in the top 10% of all addons.
The total score is out of 10.

These are intended as proxies for usefulness (the review), activity (release + commit within the last three months), viability( # of contributors), popularity (download count), interest (star count). 

Everything except for the "review" is automated. We are _very_ generous with the review part -- if there are _any_ docs or a single meaningful test, those points are given.

**Comment by joshsmith** [comment]
Wow, thanks @kategengler! This is super useful, and I didn't realize that there was a manual review part of this process. That's a really awesome service you're doing for the community.

I think the breakdown of usefulness, activity, viability, popularity, and interest are the really important takeaways here. I have to admit I was a little myopic to just activity and viability here, so this has opened my eyes some.

I'm really trying to apply some of these same ideas to projects that will be on Code Corps. The initial thought was to have these metrics be at the very least internal, so we could identify projects that need help and pinpoint where precisely they need the help. Adding in those other vectors you listed widens the usefulness of this approach.

**Comment by joshsmith** [comment]
Closing in favor of [#12](https://github.com/code-corps/code-corps-phoenix/issues/12).
