### ISSUE TITLE
PUT/PATCH for Organizations

### ISSUE THREAD

**Issue by scarfdestroyer** [code-corps/deprecated-code-corps-rails-api#223]
Currently, the `Organizations` controller has `create` and `show` actions. This needs to be expanded so we can `Update` them as well. The needed additions will be in: 
- Organization controller
- Organization policy
- Organization policy spec
- Organization request api
- Organization request api spec

**Comment by joshsmith** [comment]
Really great job writing out what you think is needed here.

Remember that ordering of what you work on is important here. Start at the spec level for the API (the most outward facing part of the change you're making). Then work your way down. Getting in the habit of red, then green, then refactor is really critical. It won't be second nature yet, but try to consciously do it in this case.

I would even recommend committing code at your save points when you feel like you've hit those tiny milestones.

**Comment by scarfdestroyer** [comment]
Satisfied by #237

**Comment by scarfdestroyer** [comment]
Closed by #237
