### ISSUE TITLE
Potentially change wording of errors

### ISSUE THREAD

**Issue by scarfdestroyer** [code-corps/deprecated-code-corps-rails-api#225]
In the `error_serializer` it catches errors and adds them to the model under the `.errors` designation. Doorkeeper has an error with `id` `NOT_AUTHORIZED` and Pundit has an error with `id` `ACCESS_DENIED`. 

The problem with the latter is that the description includes the wording "You are **not authorized** to perform this action". This can be pretty confusing when you are getting an error back that's title is one error and it's description contains the title of another.

I'm not sure as to what should be changed but I think this is something that should be discussed for the sake of making the API easy to use.

**Comment by joshsmith** [comment]
This was a really good and overlooked point that has since been resolved with #385. The wording was absolutely incorrect because _the response itself_ was incorrect.

Old issue, but still good thinking on this @scarfdestroyer.
