### ISSUE TITLE
User mentions get destroyed on each post/comment preview

### ISSUE THREAD

**Issue by begedin** [code-corps/deprecated-code-corps-rails-api#246]
The solution would be to add a status flag indicating the mention belongs to a bodyPreview or an actual post/comment body.

**Comment by begedin** [comment]
I'm thinking really hard about this, and I don't see a nice clean way to do it.

## Problems on API side
- When requesting a preview, the mentions for that post's/comment's previous `bodyPreview` field should get destroyed and new mentions should get created
- When requesting a proper save, the mentions for the `body` field should get destroyed and recreated.

This part is easily achievable by adding a status flag to each mention which is either `:preview` or `:published`. The next part is a problem.
- The response for a POST/PATCH request should include the newly generated previews belonging to post/comment, but only the subset for that specific type of request - `:preview` or `:published`. However, I'm not sure if we can specify something like that in our `render :json, include: []` request or if it's even possible to request custom options like that.
  - We can't really specify a custom scope for the `has_many` relationship on the model level, since the post itself doesn't affect the type of mentions we will be including - a published post can still have a preview requested, so we would have to include mentions with a preview state.
- There's the additional problem with the ember app handing such responses

## Ember problems
- A post is saved, 2 mentions are rendered. These get pushed to the store ember side
- The same post is saved again. 2 of the same mentions are rendered. However, since the API side destroys and recreates mentions, the 2 mentions have new IDs, so Ember sees them as new records. Additionally, the API has no way of telling ember the old mentions got destroyed, so we now have 4 mentions for that post client side. 
- The solution would be to delete (but not destroy, since we can't do an API request) those mentions before requesting both a regular save and a preview. The problem with that is, we'd have to reload the record every time we do almost anything.

Because of all that, I have a different proposed solution

## Proposed solution
- The API regenerates mentions as usual
- The mentions have a state field as described above
- The request for a post/comment save/preview does not include mentions in a response
- The ember side fetches mentions manually
  - Upon successful save or preview, the mentions are fetched as well, using `store.queryRecords` similar to how we fetch pages of a projects posts. It's cleaner, less hacky and we don't have to care that much about what we already have in the store. We simply fetch the most current mentions for a post/comment and a state (preview or published).

## Note

I looked into how github solves it, but it's not applicable for us. With Github, the whole preview body, including mentions, is rendered client side.

**Comment by joshsmith** [comment]
Can you explain a bit more why the ember side fetching manually solves the problems? Why won't the records created in ember and still in the store stick around?

Also, I'm pretty sure GitHub hits the server on preview, no?

`https://github.com/preview?markdown_unsupported=false&repository=37823327&subject=246&subject_type=Issue`

**Comment by begedin** [comment]
If we fetch it manually, we only work with the results of that fetch. We don't really care about what's in the store. 

If we go about it further, I'm not even sure mentions should be on the same level as other records, client-side. They don't really exist outside the contest of a post/comment and they get destroyed and recreated any time a post/comment goes through a change.

A record in ember is something that has some sort of persistence, but these don't.

It's not a perfect solution either way, but with a manual fetch, we at least don't need to worry about explicitly marking the existing records as deleted client-side (which would have the additional complication of first differentiating between mentions for the actual post/comment and mentions for the preview).

As for GitHub, yes, github does do a server fetch, but the response is the preview HTML which already includes mention links. We need to render our mention link urls dynamically with ember, which is an additional complication github does not have.

**Comment by joshsmith** [comment]
Got it. Makes sense.

**Comment by joshsmith** [comment]
Is this closed now by #199? Do we have remaining issues that would be better served broken out?

**Comment by begedin** [comment]
This specific bug is definitely closed. With the merge of #199, only mentions that match the "type" (`:preview` or `:published`) are being destroyed.
