### ISSUE TITLE
Add Markdown to body of Posts

### ISSUE THREAD

**Issue by joshsmith** [code-corps/deprecated-code-corps-rails-api#25]
We should be able to handle Markdown on Posts.

**Comment by begedin** [comment]
This question goes for #26 as well.

Is there some sort of special way we will be handling this? Will the server render the markdown into html and send it to the client? In that case, I'm guessing we have a `markdown` field, which can be edited and posted from the client. The server receives this, converts it to html and stores it into the `body` field?

That seems like the simplest, least intensive way to do it.

An alternative would be to not store body at all and render the markdown as html on-demand, when retrieving the post, but that would be added work for very little benefits.

**Comment by joshsmith** [comment]
Yeah, and we're going to need to some extra body processing when storing as it is, e.g. when fetching usernames.

**Comment by joshsmith** [comment]
Closed by #68.
