### ISSUE TITLE
When comment body is nil, get undefined method error

### ISSUE THREAD

**Issue by joshsmith** [code-corps/deprecated-code-corps-rails-api#256]
When the comment has no body and is getting previewed, we get:

> undefined method `scan` for nil:NilClass

**Comment by begedin** [comment]
This applies to comments and posts. If `markdown_preview` or `markdown` is nil, the body fields are as well, so the process of generating mentions fails.

![image](https://cloud.githubusercontent.com/assets/1925540/13752231/143f3cb8-ea0e-11e5-9589-42d05c601eda.png)
