### ISSUE TITLE
Do we need to reset markdown_preview and body_preview somehow if a bunch of previews was requested, but there's no actual save?

### ISSUE THREAD

**Issue by begedin** [code-corps/deprecated-code-corps-rails-api#257]
User edits a post, requests a bunch of previews, but then cancels the edit and goes back.

Next time the user edits that post, the markdown_ and body_preview fields will be set to the last saved value, which is different from the content in the markdown and body fields.

I think simplest would be to reset on show/index request, but I'm not sure.

**Comment by joshsmith** [comment]
Doing it show/index of the comment itself?

**Comment by joshsmith** [comment]
Why won't a new request for preview use the existing content?

**Comment by joshsmith** [comment]
Isn't there a case to be made that `cancel` would reset it, but anything else does not reset it?

**Comment by joshsmith** [comment]
For what it's worth, it appears that this is exactly what GitHub does. Not sure if the preview expires after some set amount of time.

**Comment by joshsmith** [comment]
@begedin bump.

**Comment by joshsmith** [comment]
@begedin just wanted to readdress this.

**Comment by begedin** [comment]
Sorry, keep missing this notification. I also noticed this is what github does, but, as you, I'm not sure about expiration. 

I think there should be an expiration, though. Otherwise, we have situations where the user wants to edit a big post, but they cant, because their edit view is showing them something completely different they may have typed in by accident a while ago. If the original post they want to edit has special formatting, then the problem is even worse.

I'd even consider going as far as making it expire almost immediately, but keeping the edit draft in the browsers session storage, so it's available while the browser is open.

**Comment by joshsmith** [comment]
I guess we can test what GitHub does. That's not a bad idea. Keep going back and seeing, including closing the browser. Then we'll know for sure how they handle it.

**Comment by begedin** [comment]
@JoshSmith I think this can be closed now, correct?
