### ISSUE TITLE
Comment and Post factories are slightly problematic due to before_validation and after_create hooks.

### ISSUE THREAD

**Issue by begedin** [code-corps/deprecated-code-corps-rails-api#261]
We should provide an easy way to create a valid post/comment of a certain status (draft, published, edited), with, or without mentions. The `:draft`, `:published` and `:edited` traits take us part of the way there right now, but there are still issues. 

The apparent ones are in `post_serializer_spec` and `generate_notifications_for_post/comment_user_mentions_spec`. We should be able to more easily create records needed in those specs. This is not the case at the moment, forcing us instead to use workarounds.

**Comment by joshsmith** [comment]
Closing as irrelevant because moving to Phoenix.
