### ISSUE TITLE
Add missing foreign key constraints to maintain data integrity

### ISSUE THREAD

**Issue by christopherstyles** [code-corps/deprecated-code-corps-rails-api#276]
Currently there are some places where cascading foreign key constraints would be helpful for maintaining referential data integrity. Generally speaking, we can look at a model’s associations to determine if a foreign key constraint is needed.

For example, a post `has_many` likes, but after the post is removed its likes should be removed as well. 

In some cases we may want to “nullify” an association, instead of deleting its data. An example of this behavior would be if a comment’s author (a `User` record) is deleted. We could either delete all of their comments, potentially leading to confusing gaps in the conversation’s UI…or we could nullify the association – settings the `user_id` to `NULL` – and choosing to display “Anonymous” instead of the user’s info, but leaving the comment itself. [[docs]](http://apidock.com/rails/ActiveRecord/ConnectionAdapters/SchemaStatements/add_foreign_key)

@JoshSmith are there any particular associations that you can think of where we would _not_ want to remove its associated data, but nullify it instead?

**Comment by joshsmith** [comment]
I am generally against deleting data altogether, so I think in almost call cases we would want to nullify the data, except in those instances where the table is a simple join (like `ProjectCategory, for example).

**Comment by joshsmith** [comment]
Closing as irrelevant because moving to Phoenix.
