### ISSUE TITLE
Add test for OPTIONS when doing DELETE

### ISSUE THREAD

**Issue by joshsmith** [code-corps/deprecated-code-corps-rails-api#282]
So we didn't specify `:delete` in `rack-cors`. And that causes some issues with Ember when doing `OPTIONS` with an `Access-Control-Request-Method:DELETE`. We need to fix this and make sure it's tested.

**Comment by joshsmith** [comment]
When this fails, you get a 404 that a route is not found.

**Comment by joshsmith** [comment]
This should be fixed in #283 which adds `DELETE` as a method to `:have_proper_preflight_options_response_headers`.

But there is NOT a test for testing `OPTIONS` with it. Not sure if it's explicitly needed since this should fix it. Want to know your thoughts @begedin.

**Comment by begedin** [comment]
I think testing that specific types of requests actually pass is within the scope of the middleware itself. On our side, it should be enough to just ensure the middleware is configured correctly.

Then again, I'm not entirely against the idea of having a single spec file where we ensure all our routes work.

**Comment by joshsmith** [comment]
I think the delete is sufficient enough to catch it.
