### ISSUE TITLE
Add login with email and pass

### ISSUE THREAD

**Issue by joshsmith** [code-corps/deprecated-code-corps-rails-api#3]
We need to add an endpoint for logging in with email and password.

**Comment by joshsmith** [comment]
I think this may be done but not as an endpoint. I'm pretty sure the OAuth credentialing flow handles it somehow, but not sure how. Probably just needs better documented.

**Comment by begedin** [comment]
#36 is related to his, but https://github.com/code-corps/code-corps-api/issues/3#issuecomment-121435947 makes me unsure if that's the solution we want.
