### ISSUE TITLE
Add New Relic

### ISSUE THREAD

**Issue by joshsmith** [code-corps/deprecated-code-corps-rails-api#300]

**Comment by joshsmith** [comment]
We need to go into Heroku and add New Relic (probably "Wayne", although I can't remember). Someone who has access needs to do this: either myself, @begedin or @christopherstyles.

**Comment by christopherstyles** [comment]
@JoshSmith I can definitely take care of this, you want to assign it to me?

**Comment by joshsmith** [comment]
Ugh I hate GitHub for this. I can't assign it to you without making you a contributor. It's yours, though!
