### ISSUE TITLE
Add database backups to Heroku

### ISSUE THREAD

**Issue by joshsmith** [code-corps/deprecated-code-corps-rails-api#302]

**Comment by christopherstyles** [comment]
I’ve scheduled a daily backup for midnight (PST):

``` zsh
% heroku pg:backups schedules -a code-corps

=== Backup Schedules
DATABASE_URL: daily at 0:00 (America/Los_Angeles)

% heroku pg:backups -a code-corps

=== Backups
ID    
----  
a002 
b001

% heroku pg:backups public-url a002 -a code-corps

The following URL will expire at 2016-06-16 20:08:01 +0000: 
  "https://xfrtu.s3.amazonaws.com/173f9fd8-c3cd-44ed-8030-857778ceb915..."
```

Since we’re currently on the `Hobby-dev` plan, backups will only be retained for 1 week.

For more info on scheduled postgres backups, see this Heroku devcenter [article](https://devcenter.heroku.com/articles/heroku-postgres-backups).

**Comment by joshsmith** [comment]
@christopherstyles did you need me to upgrade? Can't remember if I have to do it as account owner.

**Comment by christopherstyles** [comment]
@JoshSmith Yeah, an account owner will have to upgrade, due to billing. Let me know if you do, and I can migrate the data.

**Comment by joshsmith** [comment]
@christopherstyles Would you mind sharing the first part of command so I can just paste it in? I can do the `-r` and all that.

**Comment by christopherstyles** [comment]
You should be able to add an upgraded plan with:

``` zsh
% heroku addons:create heroku-postgresql:standard-0 -a code-corps
```

**Comment by joshsmith** [comment]
Did it. "The database should be available in 3-5 minutes."

**Comment by christopherstyles** [comment]
@JoshSmith Data has been migrated and the new database promoted to be primary :wink: The previous database now has an alias of `HEROKU_POSTGRESQL_RED_URL`, if we need to access it for any reason.

**Comment by joshsmith** [comment]
Okay, thanks. This good to close now?

**Comment by christopherstyles** [comment]
Yep, gtg!
