### ISSUE TITLE
Add S3 backups

### ISSUE THREAD

**Issue by joshsmith** [code-corps/deprecated-code-corps-rails-api#303]
We need to be able to create backups of our data in S3 so that we can recover it in case anything goes wrong. I'm not positive how to do this and could use thoughts from someone who knows.

**Comment by madisonsites** [comment]
What data are we trying to back up exactly?

**Comment by joshsmith** [comment]
@madisonsites All of our data in S3, mostly user images.

**Comment by joshsmith** [comment]
We should do this in Glacier. Not important enough to warrant it yet, but should be done soonish.

**Comment by joshsmith** [comment]
Closing in favor of [#17](https://github.com/code-corps/code-corps-phoenix/issues/17).
