### ISSUE TITLE
Add a long_description to Project

### ISSUE THREAD

**Issue by joshsmith** [code-corps/deprecated-code-corps-rails-api#313]
We need to add a `text` `long_description` to `Project` that takes and renders markdown. This is where project owners will give detailed information about their project like:
- What do you hope to accomplish?
- What real problem is this solving?
- What kind of support will you need, both right now and in the future?
- What risks and challenges will you face?

This can be a field on `Project` itself. We likely need to add `long_description_markdown`.

Unlike a `Post` or `Comment`, this will not generate any user mentions.

**Comment by begedin** [comment]
I'm currently working on this and, considering the usual preview behavior, gave some thoughts on how to simplify that, since we would need a total of 4 fields to mimic the current behavior.

I put them in #314 so I would like us to discuss that possibility before I continue here.
