### ISSUE TITLE
Discussion: Simplify preview behavior on various records

### ISSUE THREAD

**Issue by begedin** [code-corps/deprecated-code-corps-rails-api#314]
Test.

Right now, we have a pretty complicated set of behaviors for rendering markdown for previews, where we have separate _markdown, _markdown_preview, _html and _html_preview fields and then there's logic that determines what goes into which field depending on the API request parameters.

My suggestion is the following.

We eliminate this behavior completely. We just keep `_markdown` and `_html` fields. No extra `_preview_` fields.

When the client decides to save the record, be it post, comment or project (with soon to be added `long_description`), the markdown field is taken and the html field is generated.

For the preview action, regardless of record, we have a single `generate_html` endpoint, which the client can send the markdown to and receive the HTML as well as a set of mentions.

Basically, the client behavior would be
- when the user requests a preview, we make a manual ajax request to the preview endpoint
- when the user saves the record, we set the record.markdown field and request a regular save

This would allow us to
- eliminate the custom adapter logic for posts, comments (and soon projects)
- simplify the save logic a tiny bit
- improve on the encapsulation of the `editor-with-preview` component

This would simplify the logic greatly and also allow us consolidate html and mention rendering.

The major reason why I think this would be an improvement is that I contacted github to see how they are handling it and the reply was surprising:

> I don't think our drafts persist. We used to have a feature that was keeping drafts around forever, but we removed that feature. We may bring it back if we can make it work properly.
> 
> As for the way that could work, there are probably quite a few different approaches. I wouldn't be surprised if there are components out there that do that for you. Without the requirement to reinvent the wheel.

Basically, their drafts and previews do not really persist. What is likely happening is that the browser somehow keeps the textarea filled in.

I think this is worth the discussion at the very least.

**Comment by joshsmith** [comment]
I think they must be misinformed about this. Type a comment in here. Hit preview. Hit write. Refresh the page. I'm not sure how this would just be local storage. Maybe it is. I'm not sure.

**Comment by christopherstyles** [comment]
In the past I’ve used [marked](https://github.com/chjj/marked) to render previews on the client, saving a trip to the server. This would be an additional frontend dependency though, which I’m assuming you’re trying to avoid.

Is it necessary to store the rendered `_html` alongside the markdown `body` in the db? Would it be possible to keep only the `body` (in markdown), and render it to html as-needed? A computed `_html` attribute could be added to the API response, which should be cached eventually so the performance penalty for rendering it each time would be negated.

Looking at github: interestingly they call out to an endpoint for rendering the markdown on _hover_ of the preview button…to try and get ahead of the click I guess. I’m also seeing event handlers on keydown that add items to `sessionStorage`, but it’s difficult to know what’s going on there with minified js. I don’t see anything in session/local storage in my devtools inspector, but doesn’t seem unreasonable to explore that as an option.

**Comment by joshsmith** [comment]
@christopherstyles one of the reasons we store it is because of the ~~comment~~ mention generation, which provides indices to the front-end.

**Comment by begedin** [comment]
@JoshSmith There are additional difficulties that just occurred to me with the current system.

**Drafts are shared between all users.** With comment drafts, that could be ok, if only the owning user can edit their own comments. With post drafts, however, this really can become a problem, with one user overwriting someone else's draft.

If we want to store them, maybe a different system altogether would be preferable. Example, we could have a Draft model:

``` Ruby
# models/draft.rb

# really can't think of a good name here
belongs_to :markdown_renderable, polymorphic: true
belongs_to :user

has_many :user_mentions 
```

`Project#long_description` is a potential problem here, since we don't want mentions there, but we could always check `markdown_renderable_type` or even outright remove polymorphism and make 3 tables - `post_drafts`, `comment_drafts` and `project_drafts`.

The first, polymorphic system would simplify things, but it would still be a problem if we want, at some point, to have a model with multiple different markdown fields.

The second system is more flexible, but we may want to consider actually naming the tables `post_body_drafts`, `comment_body_drafts` and `project_long_description_drafts`.

Or, we could go with a third approach and have our `drafts` table also include a `field_name` so we know which field on the parent the draft is for.

I really, really do think we need to rework our current system, somehow.

**Comment by joshsmith** [comment]
Yes, I hadn't though through the case of multiple different people editing here like this. A good question is which edit wins. I guess the latest. But this is kind of unfortunate.

My guess is that editing happens so seldom at the same time that we don't need to worry too much about the deep details on it, but we should find some way to improve the UI at some point to make it clear that someone else is currently editing what you're working on.

I think we may want to avoid polymorphism here. What's gained in simplicity now I think we lose in flexibility later. It's more code but right now it's not super clear that these are the same entity type, even if they behave super similarly. We could at least extract out similar logic into concerns if need be.

My vote would be for the second approach.

**Comment by joshsmith** [comment]
I also like this approach because it allows us to actually create a `PostDraft` at the time of someone going to `/posts/new`.

Question: why the suggestion of `PostBodyDraft`? Is this not really a draft of the `Post` and not its `body`?

**Comment by begedin** [comment]
@JoshSmith 

> Question: why the suggestion of PostBodyDraft? Is this not really a draft of the Post and not its body?

Thinking about it, it's not really just a post body (we also need the postType), but it's not a full post draft either (we don't need a title, that part is edited and saved separately). We could make it something that also stores the title, but I'm not sure that would be an UI improvement. If anything, I'd see it as more confusing to have the title stored as a draft.

**Comment by venkatd** [comment]
From my understanding you guys have drafts for posts and comments. I think adding special conditions or types of models could add unnecessary complexity.

Another option would be to use query objects for posts and comments. So, you would have:
`PostsQuery` and `CommentsQuery`. They would take the appropriate inputs and internally filter out things you shouldn't see.

**Comment by joshsmith** [comment]
@begedin you're right, but it still feels more appropriate probably to call it a `PostDraft`.
