### ISSUE TITLE
Issues with elastic search on development

### ISSUE THREAD

**Issue by begedin** [code-corps/deprecated-code-corps-rails-api#333]
I ran into several issues when creating a user and onboarding on the development, mainly involved with elastic search on skills.
- First of all, we don't have any skill fixtures, so I had to create a few manually. We need a task for that
- [x] Create task to create some skill fixtures for development at least - #334
- I ran `brew install elasticsearch` and that worked fine
- API wasn't working and faraday was refusing to connect. Had to run `elasticsearch` in the console to get past this. Probably should add it to our `Procfile.dev`. There are other ways to run it, provided by `brew info elasticsearch`. Not sure which is best.
- Search still wasn't working. Required us to run `Skill.reindex` from the console. Not sure how to handle this. Maybe foreman should do it after running elasticsearch on startup?

**Comment by joshsmith** [comment]
We can do skill fixtures for now, but this should get resolved when we implement #320. We should have a way to bundle in the skills we actually use in production, and keep that synced up somehow.

I agree that elasticsearch should be added to `Procfile.dev` at the least.

Not sure about where the `Skill.reindex` should happen.

**Comment by madisonsites** [comment]
In my dev env with my company, we actually have to create and import the indexes ourselves, but maybe you've already done that and we're trying to troubleshoot something else.

**Comment by joshsmith** [comment]
Closing as irrelevant because moving to Phoenix.
