### ISSUE TITLE
When Project#long_description_markdown is blank, the field is saved, but _body is not updated

### ISSUE THREAD

**Issue by begedin** [code-corps/deprecated-code-corps-rails-api#336]
`Project` does not have a `presence` validation for `long_description_body` or `long_description_markdown`, which makes sense, since descriptions aren't present initially.

However, due to a bad check in the `render_markdown_to_body` method, this means that when the `_markdown` field is an empty string, it will get saved as such, but the `_body` field will remain the same as it previously was.

**Comment by joshsmith** [comment]
Closing as irrelevant because moving to Phoenix.
