### ISSUE TITLE
Update GitHub Forked Repo

### ISSUE THREAD

**Issue by kakoga** [code-corps/deprecated-code-corps-rails-api#338]
1. Make sure that your origin is your own `$ git remote -v`
   should return:
   `origin https://github.com/YourName/code-corps-api.git (fetch)
   origin  https://github.com/YourName/code-corps-api.git (push)
   upstream    https://github.com/code-corps/code-corps-api.git (fetch)
   upstream    https://github.com/code-corps/code-corps-api.git (push)`

if your origin follows as:
`origin https://github.com/YourName/code-corps-api.git (fetch)
origin  https://github.com/YourName/code-corps-api.git (push)`

skip to step 3
1. Set your origin to YOUR forked repo with:
   `git remote set-url origin https://github.com/YourName/code-corps-api.git`
2. Make sure you're on the `develop` branch, then `$ git fetch upstream` to fetch any changes.
3. Make sure that your repo is up-to-date by running `$ git log` check to ensure that the latest commit on GitHub matches your log. If it does not match, you'll need to `rebase`
4. To rebase, make sure you're on the `develop` branch and run `$ git rebase upstream/develop` then run `$ git log` to make sure that the latest commit on GitHub matches your log.

**Comment by joshsmith** [comment]
Thanks @kakoga. I realize now (after the fact, sorry!) that GitHub has some pretty decent docs on [configuring a fork to sync](https://help.github.com/articles/fork-a-repo/#step-3-configure-git-to-sync-your-fork-with-the-original-spoon-knife-repository) and [keeping your fork in sync](https://help.github.com/articles/syncing-a-fork/).

I wonder if you can't submit a PR to this and [the Ember repo](https://github.com/code-corps/code-corps-ember) that adds to the end of the first step in  [CONTRIBUTING.md](https://github.com/code-corps/code-corps-api/blob/develop/CONTRIBUTING.md#contributing) something like. "You might also want to configure your fork to stay in sync, and ensure your fork is synced with our `develop` branch (which is the default)." And include the two links to the GitHub articles above.

That should probably give as clear a picture on how to do this with far less overwhelm in our own docs. What do you think?

**Comment by kakoga** [comment]
Yes, I'll add and PR

**Comment by joshsmith** [comment]
👍 going to close this in favor of that PR.
