### ISSUE TITLE
Remove ActiveModel::Errors

### ISSUE THREAD

**Issue by rigelstpierre** [code-corps/deprecated-code-corps-rails-api#393]
ActiveModel::Errors is deprecated and will be removed in Rails 5.1. We need to remove any reference of it and replace it with something else. 

Also in `test.rb` you'll need to remove `ActiveSupport::Deprecation.silenced = true` so we can see other deprecation warnings in the future.

**Comment by joshsmith** [comment]
Closing as irrelevant because moving to Phoenix.
