### ISSUE TITLE
Find a way to deploy branch commits

### ISSUE THREAD

**Issue by joshsmith** [code-corps/deprecated-code-corps-rails-api#435]
It would be great if we could deploy and test branches on a public server so that we can review code without needing to pull it down.

**Comment by christopherstyles** [comment]
Howabout Heroku [review apps](https://devcenter.heroku.com/articles/github-integration-review-apps)?

**Comment by joshsmith** [comment]
Closing in favor of [#2](https://github.com/code-corps/code-corps-phoenix/issues/2).
