### ISSUE TITLE
Reset and forgot password errors do not follow JSON API specs

### ISSUE THREAD

**Issue by begedin** [code-corps/deprecated-code-corps-rails-api#48]
This is what they look like at the moment:

``` Ruby
def render_no_such_email_error
  render json: {errors: {email: ["doesn't exist"]}}, status: 422
end

def render_could_not_reset_password_error
  render json: {errors: {password: ["couldn't be reset"]}}, status: 422
end
```

I believe these should be replaced either by initializing a `ActiveModel::Errors` object (so we just serialize them as validation errors), or we should define our own custom errors and have the serializer serialize those.

**Comment by joshsmith** [comment]
:+1:
