### ISSUE TITLE
Change usernames/slugs to allow dashes

### ISSUE THREAD

**Issue by joshsmith** [code-corps/deprecated-code-corps-rails-api#55]
A username and slug should be allowed to have any `\w` word character: an underscore, a letter, or number. It can also have hyphens, as long as the username/slug does not begin or end with it.

A regex like this will probably work: `^[\w](?:[\w_-]*[\w])?$` for validations.

**Comment by JoshSmith** [comment]
A random test of @erearerearaer.

**Comment by JoshSmith** [comment]
@ebryn

**Comment by JoshSmith** [comment]
Testing @scarfdestroyer/asd/asd-asd

**Comment by joshsmith** [comment]
Closed by #63
