### ISSUE TITLE
When creating a user_skill, if the associated skill does not exist, should we be able to create it?

### ISSUE THREAD

**Issue by begedin** [code-corps/deprecated-code-corps-rails-api#57]
@JoshSmith

What is the user interface like in this case? Do we select a skill from a dropfdown/auto-complete when adding it to our profile, or are we also able to create a completely new skill?

**Comment by joshsmith** [comment]
For now it'll be some sort of autocomplete functionality, or selecting from a list. But I don't think we should allow users to create a bunch of random skills. We'll seed it initially and only later consider opening that up.

**Comment by begedin** [comment]
In that case, the `POST /user_skills` endpoint has this behavior covered. It requires the skill to be specified in the request and returns a validation error otherwise.

However, we do need to expose a `GET /skills` in this case, if we want an autocomplete #64.

**Comment by begedin** [comment]
Closing this in favor of #64
