### ISSUE TITLE
Expose `GET /skill_categories`

### ISSUE THREAD

**Issue by begedin** [code-corps/deprecated-code-corps-rails-api#64]
Initially, I thought it should be `GET "/skills"`, but now that I think about it, since we do have skill categories, we should probably have a `GET "/skill_categories"`, with an include of skills.

That way, through an autocomplete feature, we could fetch the data in a hierarchical form. It could go either way, though.

**Comment by begedin** [comment]
@JoshSmith 

What do you think? Should we be fetching a flat list of skills, or a list of categories with skills included? It all depends on how we want to do it on the client side and it's really not a large amount of work to do it either way.

**Comment by joshsmith** [comment]
I think maybe a list of categories with skills included for now.
