### ISSUE TITLE
Add images for posts and comments

### ISSUE THREAD

**Issue by joshsmith** [code-corps/deprecated-code-corps-rails-api#74]
A `PostImage` or `CommentImage` should be able to be uploaded as a Base64 encoded file. We'll take the original filename and save that.

We'll be replacing the first occurrence of a string like `![Uploading wx4VIGt.jpg…]()` in the client-side with the actual URL of the image. I tested this on Github and if you paste that string and then drop the file in (which generates that string again), it will replace just the first instance of it, every time.

We can create a reference to a post or comment with this model as `belongs_to`, but it will never be used in a `has_many`. We should also probably make it `belongs_to` a `User`.

The image processing will need to be asynchronous as usual, but we'll have to subscribe to some async stream for it. I think some minimal resizing down should probably be done.

The URL string should absolutely have the ID of the post or comment and the ID of the image. If we ever change URLs, we may have to rely on this (with some downtime) to do URL replacement in our `markdown` and `body` text.

But we should be trying to make these URLs as immutable as possible.

**Comment by JoshSmith** [comment]
![eso1324c](https://cloud.githubusercontent.com/assets/321667/11695000/d6bb32fe-9e61-11e5-9276-37e3ce730f49.jpg)

**Comment by joshsmith** [comment]
![pia14040](https://cloud.githubusercontent.com/assets/321667/11695115/55301640-9e62-11e5-98b4-4d11a2ba9e92.jpg)

As you can see, we can upload a file and it doesn't do any file size changes, so we probably shouldn't.

**Comment by joshsmith** [comment]
We should add an attachment validator: `validates_with AttachmentSizeValidator, attributes: :photo, less_than: 10.megabytes`
