### ISSUE TITLE
Add /user_skills endpoint

### ISSUE THREAD

**Issue by joshsmith** [code-corps/deprecated-code-corps-rails-api#8]
We need an endpoint for managing a user's skills. It should ideally handle:
- `POST`
- `DELETE`
- and `PUT`

**Comment by begedin** [comment]
Since we only have a `user_id` and `skill_id` to set on a `UserSkill` would there be a point in having a `PUT/PATCH` action?

**Comment by joshsmith** [comment]
Probably not.
