### ISSUE TITLE
Add Project model

### ISSUE THREAD

**Issue by joshsmith** [code-corps/deprecated-code-corps-rails-api#9]
A `Project` should have a:
- [x] `title:string`
- [x] `description:string`
- [ ] and an icon

**Comment by begedin** [comment]
#35 adds title and description. Since icon needs additional handling, I delayed adding that until we merge #35 and also add project edpoints.

@JoshSmith Will the icon be an image we upload, or something small enough so we can save it as a base64 string?

**Comment by joshsmith** [comment]
@begedin it will be an image a user uploads.

**Comment by joshsmith** [comment]
Icon can be implemented in #44.
